spring:
  application:
    name: Affaci



  datasource:
    url: jdbc:postgresql://localhost:5432/afaci
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9876


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html