spring:
  application:
    name: Affaci
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


  datasource:
    url: jdbc:postgresql://localhost:5432/afaci
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

server:
  port: 9876


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html

logging:
  file:
    name: logs/app.log
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: OFF


minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: products

