name: Java CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Temurin 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Build with Maven
      run: mvn -B clean package -DskipTests

    - name: Prepare SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # чтобы SSH не задавал вопросов о ключе хоста
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Copy JAR to server
      run: |
        JAR=target/Affaci-0.0.1-SNAPSHOT.jar
        ls -l "$JAR"                          # убедимся, что файл есть
        scp -v -o StrictHostKeyChecking=no \
                -o UserKnownHostsFile=/dev/null \
                "$JAR" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/bekzhan/backend/

    - name: Restart backend.service
      run: |
        ssh -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "sudo systemctl restart backend.service && systemctl status --no-pager backend.service"
