name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout репозиторий
    - name: Checkout repository
      uses: actions/checkout@v2

    # Установка JDK 17 (или другой версии)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    # Собрать проект с помощью Maven
    - name: Build with Maven
      run: mvn -B clean package -DskipTests

    - name: Add host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Verify JAR
      run: ls -l target/Affaci-0.0.1-SNAPSHOT.jar
    
    # Отправить файл JAR на сервер через SSH
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /home/bekzhan/backend
          rm -f Affaci-0.0.1-SNAPSHOT.jar
          scp -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null target/Affaci-0.0.1-SNAPSHOT.jar root@${{ secrets.SERVER_IP }}:/home/bekzhan/backend/
          sudo systemctl restart backend.service

